FROM node:18-alpine

WORKDIR /app

COPY package.json tsconfig.json next.config.js tailwind.config.js postcss.config.js ./
RUN npm install

COPY src ./src
COPY public ./public

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
